spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testuser?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: rootroot
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # 强制使用 Ant 风格路径匹配
  redis:
    host: 127.0.0.1  # 你的 Redis 服务器地址
    port: 6379         # 你的 Redis 端口
    password:          # 如果有密码，填在这里
    database: 0        # 使用的数据库索引，默认为 0
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0


mybatis:
  mapper-locations: classpath:mappers/*.xml  # 若使用XML映射文件，指定路径
  type-aliases-package: org.example.pojo.entity  # 实体类包路径